const C=window.MAPAPID_CONFIG||{};const map=L.map('map',{zoomControl:false}).setView([50.0755,14.4378],12);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);
L.control.zoom({position:'bottomleft'}).addTo(map);
let vehicles=[],markers=[],gtfs=null,routeLayer=null;const routeCache=new Map();
const $=id=>document.getElementById(id);
$('filterBtn').onclick=()=>$('sheet').classList.add('open');$('closeSheet').onclick=()=>$('sheet').classList.remove('open');
$('closeDetail').onclick=()=>{$('detail').close()};$('locate').onclick=()=>map.locate({setView:true,maxZoom:16});
['search','operator','vehicleType','line','order'].forEach(id=>$(id).addEventListener(id==='operator'||id==='vehicleType'?'change':'input',render));
function val(o,...p){for(const k of p){if(o?.[k]!=null&&o[k]!=='')return o[k]}return''}
function deep(o,key){if(!o||typeof o!=='object')return'';if(o[key]!=null&&o[key]!=='')return o[key];for(const x of Object.values(o)){if(x&&typeof x==='object'){const r=deep(x,key);if(r!==''&&r!=null)return r}}return''}
function canonTrip(id){return String(id||'').replace(/_\d{6}$/,'')}
function norm(v){const p=v.properties||v;const t=p.trip||{};const cis=t.cis||p.cis||{};const g=t.gtfs||p.gtfs||{};const vt=deep(p,'vehicle_type');const type=typeof vt==='object'?val(vt,'description_cs','description_en','id'):vt;return{id:deep(p,'vehicle_registration_number')||deep(p,'vehicle_id')||v.id||deep(p,'trip_id'),lat:v.geometry?.coordinates?.[1]??p.latitude,lng:v.geometry?.coordinates?.[0]??p.longitude,line:val(g,'route_short_name','route_id')||deep(p,'route_short_name')||deep(p,'route_id'),tripId:val(g,'trip_id')||deep(p,'gtfs_trip_id')||deep(p,'trip_id'),order:val(cis,'trip_number')||deep(p,'cis_trip_number')||deep(p,'trip_number'),ev:deep(p,'vehicle_registration_number')||deep(p,'registration_number'),operator:deep(p,'agency_name')||deep(p,'operator_name'),type,sequenceId:val(g,'sequence_id')||deep(p,'sequence_id'),delay:deep(p,'delay'),nextStop:deep(p,'next_stop'),bearing:deep(p,'bearing'),raw:v}}
function populate(){for(const [id,key,label] of [['operator','operator','Všichni dopravci'],['vehicleType','type','Všechny typy vozů']]){const s=$(id),old=s.value,vs=[...new Set(vehicles.map(v=>v[key]).filter(Boolean))].sort();s.innerHTML='<option value="">'+label+'</option>'+vs.map(x=>'<option>'+esc(x)+'</option>').join('');s.value=old}}
function filtered(){const q=$('search').value.toLowerCase().trim(),op=$('operator').value,ty=$('vehicleType').value,li=$('line').value.toLowerCase().trim(),ord=$('order').value.toLowerCase().trim();return vehicles.filter(v=>(!q||[v.line,v.order,v.ev,v.operator,v.type].some(x=>String(x).toLowerCase().includes(q)))&&(!op||v.operator===op)&&(!ty||v.type===ty)&&(!li||String(v.line).toLowerCase()===li)&&(!ord||String(v.order).toLowerCase().includes(ord)))}
function render(){markers.forEach(m=>m.remove());markers=[];const f=filtered();$('count').textContent=f.length;$('list').innerHTML=f.slice(0,100).map(v=>'<div class="vehicle" data-id="'+esc(v.id)+'"><div class="badge">'+esc(v.line||'?')+'</div><div><div class="ev">'+esc(v.ev||'Vůz bez ev. č.')+'</div><div class="muted">'+esc([v.operator,v.type].filter(Boolean).join(' · '))+'</div></div><div class="muted">'+esc(v.order||'')+'</div></div>').join('');document.querySelectorAll('.vehicle').forEach(e=>e.onclick=()=>openVehicle(e.dataset.id));for(const v of f){if(!Number.isFinite(+v.lat)||!Number.isFinite(+v.lng))continue;const icon=L.divIcon({className:'',html:'<div class="marker">'+esc(v.line||'?')+'</div>',iconSize:[28,28]});const m=L.marker([v.lat,v.lng],{icon}).addTo(map).on('click',()=>openVehicle(v.id));markers.push(m)}}
function tripKey(id){if(!gtfs)return null;if(gtfs.trips?.[id])return id;return gtfs.aliases?.[canonTrip(id)]||null}
async function loadTrip(key){const ref=gtfs?.trips?.[key];if(!ref?.f)return null;if(!routeCache.has(ref.f)){const r=await fetch('./data/routes/'+ref.f,{cache:'no-store'});if(!r.ok)throw Error('Detail trasy HTTP '+r.status);routeCache.set(ref.f,await r.json())}const c=routeCache.get(ref.f),t=c.trips?.[key];if(!t)return null;return {...t,shape:c.shapes?.[t.shape_id]||[]}}
function showRoute(trip){if(routeLayer){routeLayer.remove();routeLayer=null}if(!trip?.shape?.length)return;routeLayer=L.polyline(trip.shape,{weight:5,opacity:.75}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[35,35],maxZoom:15})}
function delayText(d){if(d===''||d==null)return'';const n=Number(d);if(!Number.isFinite(n))return String(d);const m=Math.round(n/60);return m===0?'včas':(m>0?'zpoždění +'+m+' min':'náskok '+m+' min')}
async function openVehicle(id){const v=vehicles.find(x=>String(x.id)===String(id));if(!v)return;const key=tripKey(v.tripId);let trip=null;try{if(key)trip=await loadTrip(key)}catch(e){console.error(e)}const block=key?gtfs?.trips?.[key]?.b:null,runs=block?gtfs.blocks?.[block]:null;showRoute(trip);const stops=trip?.stops||[];$('detailBody').innerHTML='<h2>'+esc(v.ev?('Vůz '+v.ev):'Vozidlo')+'</h2><p><b>Linka '+esc(v.line||'?')+'</b> · '+esc(v.order||'pořadí neznámé')+'</p>'+(v.delay!==''?'<p><b>'+esc(delayText(v.delay))+'</b></p>':'')+(v.nextStop?'<p>Následuje: '+esc(typeof v.nextStop==='object'?(v.nextStop.name||v.nextStop.id||''):v.nextStop)+'</p>':'')+(stops.length?'<h3>Trasa spoje</h3><div class="timeline">'+stops.map(s=>'<div class="trip"><b>'+esc(s.n||s.id)+'</b> '+esc(s.a||s.d||'')+'</div>').join('')+'</div>':'')+(runs?'<h3>Plánovaný oběh</h3><div class="timeline">'+runs.map(r=>'<div class="trip '+(r.trip_id===key?'now':'')+'"><b>'+esc(r.route||'?')+'</b> '+esc(r.start||'')+'–'+esc(r.end||'')+'<br><span class="muted">'+esc(r.headsign||'')+'</span></div>').join('')+'</div>':'<p class="muted">Pro tento spoj zatím nemám navázaný GTFS oběh.</p>');$('detail').showModal()}
async function load(){try{if(C.gtfsDataUrl&&!gtfs){const r=await fetch(C.gtfsDataUrl,{cache:'no-store'});if(r.ok)gtfs=await r.json()}if(!C.realtimeProxyUrl){$('status').textContent='Realtime čeká na nastavení bezpečného API proxy.';render();return}const r=await fetch(C.realtimeProxyUrl);if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();vehicles=(j.features||j).map(norm);populate();$('status').textContent='Aktuálně '+vehicles.length+' vozidel · obnoveno '+new Date().toLocaleTimeString('cs-CZ');render()}catch(e){$('status').textContent='Chyba načítání: '+e.message}}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
load();setInterval(load,30000);