const C=window.MAPAPID_CONFIG||{};const map=L.map('map',{zoomControl:false}).setView([50.0755,14.4378],12);
L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'© OpenStreetMap © CARTO',subdomains:'abcd',maxZoom:20}).addTo(map);
L.control.zoom({position:'bottomleft'}).addTo(map);
let vehicles=[],gtfs=null,routeLayer=null,selectedId=null,selectedTrip=null,lastRefresh=0,nextRefresh=0;const routeCache=new Map(),markerMap=new Map();let primary=localStorage.getItem('mapapid-marker')||'line',typeChip='';const $=id=>document.getElementById(id);
$('filterBtn').onclick=()=>$('sheet').classList.add('open');$('closeSheet').onclick=()=>$('sheet').classList.remove('open');$('locate').onclick=()=>map.locate({setView:true,maxZoom:16});$('backTrip').onclick=()=>$('tripPage').hidden=true;
$('markerPrimary').value=primary;$('markerPrimary').onchange=e=>{primary=e.target.value;localStorage.setItem('mapapid-marker',primary);render()};
['search','operator','vehicleType','line','order'].forEach(id=>$(id).addEventListener(id==='operator'||id==='vehicleType'?'change':'input',render));
document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>{typeChip=b.dataset.type;document.querySelectorAll('.chips button').forEach(x=>x.classList.toggle('active',x===b));render()});
map.on('zoomend',renderMarkers);
function canonTrip(id){return String(id||'').replace(/_\d{6}$/,'')}
function norm(v){const p=v.properties||v,t=p.trip||{},cis=t.cis||{},g=t.gtfs||{},lp=p.last_position||{},vt=t.vehicle_type||{};const seq=t.sequence_id;return{id:t.vehicle_registration_number??v.id??g.trip_id,lat:v.geometry?.coordinates?.[1],lng:v.geometry?.coordinates?.[0],line:g.route_short_name||g.route_id||'',tripId:g.trip_id||'',order:seq!==null&&seq!==undefined&&seq!==''?seq:(cis.trip_number??''),ev:t.vehicle_registration_number??'',operator:t.agency_name?.real||t.agency_name?.scheduled||'',type:vt.description_cs||vt.description_en||vt.id||'',sequenceId:seq??'',delay:lp.delay?.actual??'',lastStop:lp.last_stop||null,nextStop:lp.next_stop||null,bearing:lp.bearing??'',headsign:g.trip_headsign||'',observed:lp.origin_timestamp||'',raw:v}}
function populate(){for(const [id,key,label] of [['operator','operator','Všichni dopravci'],['vehicleType','type','Všechny typy vozů']]){const s=$(id),old=s.value,vs=[...new Set(vehicles.map(v=>v[key]).filter(Boolean))].sort();s.innerHTML='<option value="">'+label+'</option>'+vs.map(x=>'<option>'+esc(x)+'</option>').join('');s.value=old}}
function filtered(){const q=$('search').value.toLowerCase().trim(),op=$('operator').value,ty=$('vehicleType').value,li=$('line').value.toLowerCase().trim(),ord=$('order').value.toLowerCase().trim();return vehicles.filter(v=>(!q||[v.line,v.order,v.ev,(v.line&&v.order?v.line+'/'+v.order:''),v.operator,v.type].some(x=>String(x).toLowerCase().includes(q)))&&(!op||v.operator===op)&&(!ty||v.type===ty)&&(!typeChip||String(v.type).toLowerCase().includes(typeChip))&&(!li||String(v.line).toLowerCase()===li)&&(!ord||String(v.order).toLowerCase().includes(ord)))}
function markerHtml(v){const zoom=map.getZoom(),main=primary==='ev'?(v.ev||'?'):(v.line||'?'),second=primary==='ev'?(v.line||''):(v.ev||'');return '<div class="marker '+(zoom>=15?'dual':'')+'"><span>'+esc(main)+'</span>'+(zoom>=15&&second?'<span class="secondary">'+esc(second)+'</span>':'')+'</div>'}
function renderMarkers(){const f=filtered(),ids=new Set(f.map(v=>String(v.id)));for(const [id,m] of markerMap){if(!ids.has(id)){m.remove();markerMap.delete(id)}}for(const v of f){if(!Number.isFinite(+v.lat)||!Number.isFinite(+v.lng))continue;const id=String(v.id),icon=L.divIcon({className:'',html:markerHtml(v),iconSize:map.getZoom()>=15?[38,30]:[27,27]});let m=markerMap.get(id);if(!m){m=L.marker([v.lat,v.lng],{icon}).addTo(map).on('click',()=>selectVehicle(id));markerMap.set(id,m)}else{m.setIcon(icon);const old=m.getLatLng(),dest=L.latLng(v.lat,v.lng);if(old.distanceTo(dest)>1){const start=performance.now(),dur=900;const tick=n=>{const t=Math.min(1,(n-start)/dur),e=1-Math.pow(1-t,3);m.setLatLng([old.lat+(dest.lat-old.lat)*e,old.lng+(dest.lng-old.lng)*e]);if(t<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)}}}}
function render(){const f=filtered();$('count').textContent=f.length;$('list').innerHTML=f.slice(0,100).map(v=>'<div class="vehicle" data-id="'+esc(v.id)+'"><div class="badge">'+esc(v.line||'?')+'</div><div><div class="ev">'+esc(v.ev||'Vůz bez ev. č.')+'</div><div class="muted">'+esc([v.operator,v.type].filter(Boolean).join(' · '))+'</div></div><div class="muted">'+esc(v.order||'')+'</div></div>').join('');document.querySelectorAll('.vehicle').forEach(e=>e.onclick=()=>selectVehicle(e.dataset.id));renderMarkers()}
function tripKey(id){if(!gtfs)return null;if(gtfs.trips?.[id])return id;return gtfs.aliases?.[canonTrip(id)]||null}
async function loadTrip(key){const ref=gtfs?.trips?.[key];if(!ref?.f)return null;if(!routeCache.has(ref.f)){const r=await fetch('./data/routes/'+ref.f,{cache:'no-store'});if(!r.ok)throw Error('Detail trasy HTTP '+r.status);routeCache.set(ref.f,await r.json())}const c=routeCache.get(ref.f),t=c.trips?.[key];if(!t)return null;return {...t,shape:c.shapes?.[t.shape_id]||[]}}
function showRoute(trip){if(routeLayer){routeLayer.remove();routeLayer=null}if(!trip?.shape?.length)return;routeLayer=L.polyline(trip.shape,{weight:6,opacity:.9,color:'#FF3636',lineCap:'round',lineJoin:'round'}).addTo(map)}
function delayText(d){if(d===''||d==null)return'';const n=Number(d);if(!Number.isFinite(n))return String(d);const m=Math.round(n/60);return Math.abs(n)<30?'včas':(m>0?'zpoždění +'+m+' min':'náskok '+Math.abs(m)+' min')}
function secTime(t,delta){if(!t||delta==null||delta==='')return'';const m=String(t).match(/^(\d+):(\d+)(?::(\d+))?$/);if(!m)return'';let x=+m[1]*3600 + +m[2]*60 + +(m[3]||0) + Number(delta);x=((x%86400)+86400)%86400;return String(Math.floor(x/3600)).padStart(2,'0')+':'+String(Math.floor(x%3600/60)).padStart(2,'0')}
function shortTime(t){return String(t||'').replace(/^(\d{1,2}:\d{2}).*$/,'$1')}
function stopRows(stops,v){const next=Number(v.nextStop?.sequence||0),last=Number(v.lastStop?.sequence||0),delay=Number(v.delay||0),lastDelay=v.raw?.properties?.last_position?.delay?.last_stop_arrival;return stops.map((s,i)=>{const seq=i+1,plan=s.a||s.d||'',past=last&&seq<=last,future=next&&seq>=next,isLast=last&&seq===last,isNext=next&&seq===next;let live='',kind='';if(isLast&&lastDelay!=null){live=secTime(plan,lastDelay);kind='actual'}else if(future&&Number.isFinite(delay)){live=secTime(plan,delay);kind=delay>30?'late':delay<-30?'early':'ontime'}return '<div class="stop-row '+(isNext?'now ':'')+(past?'past ':'')+'"><div class="stop-dot"></div><div class="stop-name">'+esc(s.n||s.id)+'</div><div class="stop-times"><span class="planned">'+esc(shortTime(plan))+'</span>'+(live?'<span class="live '+kind+'">'+esc(live)+'</span>':'')+'</div></div>'}).join('')}
async function selectVehicle(id){selectedId=String(id);const v=vehicles.find(x=>String(x.id)===selectedId);if(!v)return;const key=tripKey(v.tripId);selectedTrip=null;try{if(key)selectedTrip=await loadTrip(key)}catch(e){console.error(e)}showRoute(selectedTrip);renderCard()}
function nextName(v){return selectedTrip?.stops?.find(s=>s.id===v.nextStop?.id)?.n||v.nextStop?.id||'—'}
function ageText(v){const t=Date.parse(v.observed);if(!Number.isFinite(t))return'';const s=Math.max(0,Math.round((Date.now()-t)/1000));return s<5?'právě teď':s<60?'před '+s+' s':'před '+Math.floor(s/60)+' min'}
function renderCard(){const v=vehicles.find(x=>String(x.id)===selectedId),el=$('vehicleCard');if(!v){el.hidden=true;return}el.hidden=false;el.innerHTML='<div class="vc-top"><div class="vc-route">'+esc(v.line||'?')+'/'+esc(v.order||'?')+'</div><div class="vc-main"><b>'+esc(v.ev||'Vozidlo')+'</b><div>→ '+esc(v.headsign||'—')+'</div></div><div class="vc-delay '+(Number(v.delay)>30?'late-text':'')+'">'+esc(delayText(v.delay)||'—')+'</div></div><div class="vc-next"><span>Následuje <b>'+esc(nextName(v))+'</b></span><span>'+esc(v.nextStop?.sequence||'')+'</span></div><div class="vc-actions"><button id="openSchedule">Jízdní řád</button><button id="openRun">Oběh</button><button id="followVehicle">Sledovat</button><span class="vc-age">data '+esc(ageText(v))+'</span></div>';$('openSchedule').onclick=()=>openTripPage('schedule');$('openRun').onclick=()=>openTripPage('run');$('followVehicle').onclick=()=>{if(Number.isFinite(+v.lat))map.setView([v.lat,v.lng],Math.max(map.getZoom(),15))}}
function openTripPage(tab){const v=vehicles.find(x=>String(x.id)===selectedId);if(!v)return;$('tripPage').hidden=false;$('tripTitle').textContent=(v.line||'?')+'/'+(v.order||'?')+' · '+(v.ev||'');const schedule='<div class="schedule-head"><span>Zastávka</span><span>JŘ&nbsp;&nbsp; skutečnost / odhad</span></div><div class="timeline">'+stopRows(selectedTrip?.stops||[],v)+'</div>';const tech='<dl class="tech-grid"><dt>Trip ID</dt><dd>'+esc(v.tripId||'—')+'</dd><dt>Sequence ID</dt><dd>'+esc(v.sequenceId||'—')+'</dd><dt>Dopravce</dt><dd>'+esc(v.operator||'—')+'</dd><dt>Typ</dt><dd>'+esc(v.type||'—')+'</dd></dl>';const run='<div class="route-note"><b>Oběh vozidla</b><br>Aktuální trip je připraven jako kotva. Navázání sousedních tripů podle sekvence PID GTFS doplníme po ověření hranic výkonu.</div>';$('tripPageBody').innerHTML='<div class="trip-body"><div class="trip-tabs"><button data-tab="schedule">Spoj</button><button data-tab="run">Oběh</button><button data-tab="vehicle">Vůz</button></div><div id="tabBody">'+(tab==='run'?run:tab==='vehicle'?tech:schedule)+'</div></div>';document.querySelectorAll('.trip-tabs button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.onclick=()=>openTripPage(b.dataset.tab)})}
async function load(){try{if(C.gtfsDataUrl&&!gtfs){const r=await fetch(C.gtfsDataUrl,{cache:'no-store'});if(r.ok)gtfs=await r.json()}if(!C.realtimeProxyUrl){$('status').textContent='Realtime čeká na nastavení bezpečného API proxy.';render();return}const r=await fetch(C.realtimeProxyUrl);if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();vehicles=(j.features||j).map(norm);lastRefresh=Date.now();nextRefresh=lastRefresh+30000;populate();$('status').textContent='Aktuálně '+vehicles.length+' vozidel · '+new Date().toLocaleTimeString('cs-CZ');render();if(selectedId)renderCard()}catch(e){$('status').textContent='Chyba načítání: '+e.message}}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
load();setInterval(load,30000);setInterval(()=>{const s=Math.max(0,Math.ceil((nextRefresh-Date.now())/1000));$('refreshMini').textContent=lastRefresh?'↻ '+s+' s':'…';if(selectedId)renderCard()},1000);